// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC16Otx7fyreeDm8BmgGsnwuN_nf9Aq5BI',
    appId: '1:915695159918:web:1947ac72655b7b2eb5f47f',
    messagingSenderId: '915695159918',
    projectId: 'taskaroo-todo-app',
    authDomain: 'taskaroo-todo-app.firebaseapp.com',
    storageBucket: 'taskaroo-todo-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB31KERs5Ce2PvQzLGaA-2oQJ-5RMa5Z0s',
    appId: '1:915695159918:android:e20437a7e2abe3c8b5f47f',
    messagingSenderId: '915695159918',
    projectId: 'taskaroo-todo-app',
    storageBucket: 'taskaroo-todo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEDGOsifvosKaMRhdiLkYzbhVTIzE7uIg',
    appId: '1:915695159918:ios:15632d55d92498b1b5f47f',
    messagingSenderId: '915695159918',
    projectId: 'taskaroo-todo-app',
    storageBucket: 'taskaroo-todo-app.firebasestorage.app',
    iosBundleId: 'com.example.taskaroo',
  );
}
